### ISSUE TITLE
BDZ theme bug w/ WooCommerce Product Images

### ISSUE THREAD

**Issue by Laurel-Summit-Media** [soflyy/breakdance-zero-theme#11]
Using the breakdance zero theme, breakdance, and WooCommerce. We have observed a bug with the theme which causes any product images to disappear from the products pages in WooCommerce in WP Admin. Unable to add or remove product images unless the BDZ theme is disabled by removing theme support in BD or by enabling theme support in BD and by switching to a default WordPress theme like the 2023 theme. 

Apparent that the BDZ theme is removing the WooCommerce product images on all products in the WooCommerce store and no way to update these images unless you disable the theme.

**Comment by Spellhammer** [comment]
@Laurel-Summit-Media Thanks for the report. Since we don't actively monitor issues in this repo, I've logged an internal bug report linking to this and will close this issue.
